booktime/urls.py
"""booktime URL Configuration"""
from django.conf.urls import include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('ebooks/', include('ebook.urls'), name='ebook_root'),
    path('audiobooks/', include('audiobook.urls'), name='audiobook_root'),
]

main/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic import TemplateView, RedirectView

import main.forms
import main.views

urlpatterns = [
                  url(r"about-us/",
                      TemplateView.as_view(template_name="about_us.html"),
                      name='about_us'),
                  path("",
                       TemplateView.as_view(template_name="home.html"),
                       name="home"),
                  path("contact-us/",
                       main.views.ContactUs.as_view(),
                       name="contact_us"),
                  path("accounts/", RedirectView.as_view(url='login', permanent=True, )),
                  path('accounts/signup/',
                       main.views.SignupView.as_view(),
                       name="signup"),
                  path("accounts/login/",
                       auth_views.LoginView.as_view(template_name="account/login.html",
                                                    form_class=main.forms.AuthenticationForm,
                                                    redirect_authenticated_user=True),
                       name="login",
                       kwargs={'redirect_authenticated_user': True}),
                  path("accounts/logout/",
                       auth_views.LogoutView.as_view(),
                       name="logout"),
                  path("accounts/profile/",
                       main.views.ProfileView.as_view(),
                       name="profile", ),
                  # path("authed/", RedirectView.as_view(url='home', permanent=False)),
                  path(
                      "address/",
                      main.views.AddressListView.as_view(),
                      name="address_list",
                  ),
                  path(
                      "address/create/",
                      main.views.AddressCreateView.as_view(),
                      name="address_create",
                  ),
                  path(
                      "address/<int:pk>/",
                      main.views.AddressUpdateView.as_view(),
                      name="address_update",
                  ),
                  path(
                      "address/<int:pk>/delete/",
                      main.views.AddressDeleteView.as_view(),
                      name="address_delete",
                  ),
                  path(
                      "add_to_basket/",
                      main.views.add_to_basket,
                      name="add_to_basket",
                  ),
                  path('basket/',
                       main.views.manage_basket,
                       name="basket"),
                  path(
                      "order/done/",
                      TemplateView.as_view(template_name="main/done_order.html"),
                      name="checkout_done",
                  ),
                  path(
                      "order/address_select/",
                      main.views.AddressSelectionView.as_view(),
                      name="address_select",
                  ),
                  # path(
                  #     "order_dashboard/",
                  #     main.views.OrderView.as_view(),
                  #     name="order_dashboard",
                  # ),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
import logging

from django.contrib.auth.models import (AbstractUser, BaseUserManager, )
from django.core import exceptions
from django.core.validators import MinValueValidator
from django.db import models
from django.db.models import Count, Sum

from ebook.models import Ebook

logger = logging.getLogger(__name__)


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError("The given email must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError(
                "Superuser must have is_staff=True."
            )
        if extra_fields.get("is_superuser") is not True:
            raise ValueError(
                "Superuser must have is_superuser=True."
            )

        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    username = None
    email = models.EmailField("email address", unique=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = UserManager()

    @property
    def is_employee(self):
        return self.is_active and (
                self.is_superuser
                or self.is_staff
                and self.groups.filter(name="Employees").exists()
        )

    @property
    def is_dispatcher(self):
        return self.is_active and (
                self.is_superuser
                or self.is_staff
                and self.groups.filter(name="Dispatchers").exists()
        )


class Address(models.Model):
    SUPPORTED_COUNTRIES = (
        ("in", "India"),
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=60)
    address1 = models.CharField("Address line 1", max_length=60)
    address2 = models.CharField(
        "Address line 2", max_length=60, blank=True
    )
    zip_code = models.CharField(
        "ZIP / Postal code", max_length=12
    )
    city = models.CharField(max_length=60)
    country = models.CharField(
        max_length=3, choices=SUPPORTED_COUNTRIES
    )

    def __str__(self):
        return ", ".join(
            [
                self.name,
                self.address1,
                self.address2,
                self.zip_code,
                self.city,
                self.country,
            ]
        )


class Basket(models.Model):
    OPEN = 10
    SUBMITTED = 20
    STATUSES = ((OPEN, "Open"), (SUBMITTED, "Submitted"))
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, blank=True, null=True
    )
    status = models.IntegerField(choices=STATUSES, default=OPEN)

    def is_empty(self):
        return self.basketline_set.all().count() == 0

    def count(self):
        return sum(i.quantity for i in self.basketline_set.all())

    def create_order(self, billing_address, shipping_address):
        if not self.user:
            raise exceptions.BasketException(
                "Cannot create order without user"
            )

        logger.info(
            "Creating order for basket_id=%d"
            ", shipping_address_id=%d, billing_address_id=%d",
            self.id,
            shipping_address.id,
            billing_address.id,
        )

        order_data = {
            "user": self.user,
            "billing_name": billing_address.name,
            "billing_address1": billing_address.address1,
            "billing_address2": billing_address.address2,
            "billing_zip_code": billing_address.zip_code,
            "billing_city": billing_address.city,
            "billing_country": billing_address.country,
            "shipping_name": shipping_address.name,
            "shipping_address1": shipping_address.address1,
            "shipping_address2": shipping_address.address2,
            "shipping_zip_code": shipping_address.zip_code,
            "shipping_city": shipping_address.city,
            "shipping_country": shipping_address.country,
        }
        order = Order.objects.create(**order_data)
        c = 0
        for line in self.basketline_set.all():
            for item in range(line.quantity):
                order_line_data = {
                    "order": order,
                    "product": line.product,
                }
                order_line = OrderLine.objects.create(
                    **order_line_data
                )
                c += 1

        logger.info(
            "Created order with id=%d and lines_count=%d",
            order.id,
            c,
        )

        self.status = Basket.SUBMITTED
        self.save()
        return order


class BasketLine(models.Model):
    basket = models.ForeignKey(Basket, on_delete=models.CASCADE)
    product = models.ForeignKey(
        Ebook, on_delete=models.CASCADE
    )
    quantity = models.PositiveIntegerField(
        default=1, validators=[MinValueValidator(1)]
    )


class Order(models.Model):
    NEW = 10
    PAID = 20
    DONE = 30
    STATUSES = ((NEW, "New"), (PAID, "Paid"), (DONE, "Done"))
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.IntegerField(choices=STATUSES, default=NEW)

    billing_name = models.CharField(max_length=60)
    billing_address1 = models.CharField(max_length=60)
    billing_address2 = models.CharField(
        max_length=60, blank=True
    )
    billing_zip_code = models.CharField(max_length=12)
    billing_city = models.CharField(max_length=60)
    billing_country = models.CharField(max_length=3)

    shipping_name = models.CharField(max_length=60)
    shipping_address1 = models.CharField(max_length=60)
    shipping_address2 = models.CharField(
        max_length=60, blank=True
    )
    shipping_zip_code = models.CharField(max_length=12)
    shipping_city = models.CharField(max_length=60)
    shipping_country = models.CharField(max_length=3)

    date_updated = models.DateTimeField(auto_now=True)
    date_added = models.DateTimeField(auto_now_add=True)

    last_spoken_to = models.ForeignKey(
        User,
        null=True,
        related_name="cs_chats",
        on_delete=models.SET_NULL,
    )

    @property
    def mobile_thumb_url(self):
        products = [i.product for i in self.lines.all()]
        if products:
            img = products[0].productimage_set.first()
            if img:
                return img.thumbnail.url

    @property
    def summary(self):
        product_counts = self.lines.values(
            "product__name"
        ).annotate(c=Count("product__name"))
        pieces = []
        for pc in product_counts:
            pieces.append(
                "%s x %s" % (pc["c"], pc["product__name"])
            )
        return ", ".join(pieces)

    @property
    def total_price(self):
        res = self.lines.aggregate(
            total_price=Sum("product__price")
        )
        return res["total_price"]


class OrderLine(models.Model):
    NEW = 10
    PROCESSING = 20
    SENT = 30
    CANCELLED = 40
    STATUSES = (
        (NEW, "New"),
        (PROCESSING, "Processing"),
        (SENT, "Sent"),
        (CANCELLED, "Cancelled"),
    )

    order = models.ForeignKey(
        Order, on_delete=models.CASCADE, related_name="lines"
    )
    product = models.ForeignKey(
        Ebook, on_delete=models.PROTECT
    )
    status = models.IntegerField(choices=STATUSES, default=NEW)

main/forms.py
import logging

from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.forms import (UserCreationForm as DjangoUserCreationForm)
from django.contrib.auth.forms import UsernameField
from django.core.mail import send_mail
from django.forms import inlineformset_factory

from . import models
from . import widgets

logger = logging.getLogger(__name__)


class ContactForm(forms.Form):
    name = forms.CharField(label='Your Name', max_length=100)
    email = forms.EmailField(label="Enter your E-mail id", max_length=254)
    message = forms.CharField(
        max_length=500, widget=forms.Textarea
    )

    def send_mail(self):
        logger.info("Sending email to customer service")

        message = "From: {0}\nEmail: {1}\nMessage: {2}".format(self.cleaned_data["name"],
                                                               self.cleaned_data["email"],
                                                               self.cleaned_data["message"], )
        send_mail("Site message", message, "site@booktime.domain", [self.cleaned_data["email"]],
                  fail_silently=False, )


class UserCreationForm(DjangoUserCreationForm):
    class Meta(DjangoUserCreationForm.Meta):
        model = models.User
        fields = ("email",)
        field_classes = {"email": UsernameField}

    def send_mail(self):
        logger.info("Sending signup email for email=%s", self.cleaned_data["email"], )
        message = "Welcome {}".format(self.cleaned_data["email"])
        send_mail("Welcome to BookTime", message, "site@booktime.domain", [self.cleaned_data["email"]],
                  fail_silently=True, )


class AuthenticationForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(strip=False, widget=forms.PasswordInput)

    def __init__(self, request=None, *args, **kwargs):
        self.request = request
        self.user = None
        super().__init__(*args, **kwargs)

    def clean(self):
        email = self.cleaned_data.get("email")

        password = self.cleaned_data.get("password")
        if email is not None and password:
            self.user = authenticate(self.request, email=email, password=password)
        if self.user is None:
            raise forms.ValidationError("Invalid email/password combination.")
        logger.info("Authentication successful for email=%s", email)
        return self.cleaned_data

    def get_user(self):
        return self.user


BasketLineFormSet = inlineformset_factory(
    models.Basket,
    models.BasketLine,
    fields=("quantity",),
    extra=0,
    widgets={"quantity": widgets.PlusMinusNumberInput()},
)


class AddressSelectionForm(forms.Form):
    billing_address = forms.ModelChoiceField(
        queryset=None)
    shipping_address = forms.ModelChoiceField(
        queryset=None)

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        queryset = models.Address.objects.filter(user=user)
        self.fields['billing_address'].queryset = queryset
        self.fields['shipping_address'].queryset = queryset

templates/main/address_confirm_delete.html
{% extends "base.html" %}
{% block content %}
<h2>Delete address</h2>
<form method="POST">
    {% csrf_token %}
    <p>Are you sure you want to delete it?</p>
    <button class="btn btn-­primary" type="submit">Submit
    </button>
</form>
{% endblock content %}

templates/main/address_form.html
{% extends "base.html" %}
{% block content %}
<h2>Add a new address</h2>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-­primary" type="submit">Submit</button>
</form>
{% endblock content %}

templates/main/address_list.html
{% extends "base.html" %}
{% block content %}
<h1>List of your addresses:</h1>
{% for address in object_list %}
<p>
    {{ address.name }}<br>
    {{ address.address1 }}<br>
    {{ address.address2 }}<br>
    {{ address.city }}<br>
    {{ address.get_country_display }}<br>
</p>
<p>
    <a href="{% url 'address_update' address.id %}">Update
        address</a>
</p>
<p>
    <a href="{% url 'address_delete' address.id %}">Delete
        address</a>
</p>
{% if not forloop.last %}
<hr>
{% endif %}
{% endfor %}
<p>
    <a href="{% url 'address_create' %}">Add new address</a>
</p>
{% endblock content %}

templates/main/address_select.html
{% extends "base.html" %}
{% block content %}
<h2>Select the billing/shipping addresses</h2>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}

    <button class="btn btn-­primary" type="submit">Submit</button>
    <a class="btn btn-primary" href="{% url 'address_create' %}">Add a new one</a>
</form>
{% endblock content %}

templates/main/address_update.html
{% extends "base.html" %}
{% block content %}
<h2>Add a new address</h2>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-­primary" type="submit">Submit</button>
</form>
{% endblock content %}

templates/main/basket.html
{% extends "base.html" %}
{% block content %}
<h2>Basket</h2>
{% if formset %}
<p>You can adjust the quantities below.</p>
<form method="POST">
    {% csrf_token %}
    {{ formset.management_form }}
    {% for form in formset %}
    <p>
        {{ form.instance.ebook.name }}
        {{ form }}
    </p>
    {% endfor %}

    <button class="btn btn-­default" type="submit">Update basket</button>
    {% if user.is_authenticated %}
    <a class="btn btn-primary" href="{% url 'address_select' %}">Place order</a>
    {% else %}
    <a class="btn btn-primary" href="{% url 'signup' %}?next={% url 'address_select' %}">Signup</a>
    <a class="btn btn-primary" href="{% url 'login' %}?next={% url 'address_select' %}">Login</a>
    {% endif %}
</form>
{% else %}
<p>You have no items in the basket.</p>
{% endif %}
{% endblock content %}
{% block js %}
{% if formset %}
{{ formset.media }}
{% endif %}
{% endblock js %}

templates/main/contact_form.html
{% extends "base.html" %}
{% block content %}
<h2>Contact us</h2>
<p>Please fill the form below to contact us</p>
<form method="POST"> {% csrf_token %}
    <div class="form-group"> {{ form.name.label_tag }}
        <input class="form-control {% if form.name.errors %}is-invalid{% endif %}"
               id="id_name"
               name="name" placeholder="Your name" type="text"
               value="{{ form.name.value| default:'' }}">
        {% if form.name.errors %}
        <div class="invalid-feedback"> {{ form.name.errors }}</div>
        {% endif %}
    </div>
    <div class="form-group"> {{ form.email.label_tag }}
        <input class="form-control {% if form.email.errors %}is-invalid{% endif %}"
               id="id_email"
               name="email" placeholder="Email" type="email"
               value="{{ form.email.value| default:'' }}">
        {% if form.email.errors %}
        <div class="invalid-feedback"> {{ form.email.errors }}</div>
        {% endif %}
    </div>
    <div class="form-group"> {{ form.message.label_tag }}
        <textarea class="form-control {% if form.message.errors %} is- invalid{% endif %}" id="id_message"
                  name="message" placeholder="Message" rows="3">{{ form.message.value|default:''}}</textarea>
        {% if form.message.errors %}
        <div class="invalid-feedback"> {{ form.message.errors }}</div>
        {% endif %}
    </div>
    <button class="btn btn-primary" type="submit">Submit</button>
</form>
{% endblock content %}

templates/main/done_order.html
{% extends "base.html" %}
{% block content %}
<p>Thanks for your order.</p>
{% endblock content %}