audiobook/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.views.generic import DetailView

import audiobook.models
from . import views

urlpatterns = [
                  path("",
                       views.AudioBookListView.as_view(),
                       name="audiobooks", ),
                  path("<slug:tag>",
                       views.AudioBookListView.as_view(),
                       name="audiobooks", ),
                  path("audiobook/<slug:slug>/",
                       DetailView.as_view(model=audiobook.models.Audiobook),
                       name="audiobook", ),
                  path("audiobook_viewer/", audiobook.views.AudiobookAllShowView.as_view(),
                       name='all_audiobook_viewer'),
                  path("audiobook_viewer/<slug:slug>/", audiobook.views.AudiobookShowView.as_view(), name='audiobook_viewer'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

booktime/urls.py
"""booktime URL Configuration"""
from django.conf.urls import include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('ebooks/', include('ebook.urls'), name='ebook_root'),
    path('audiobooks/', include('audiobook.urls'), name='audiobook_root'),
]

main/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic import TemplateView, RedirectView

import main.forms
import main.views

urlpatterns = [
                  url(r"about-us/",
                      TemplateView.as_view(template_name="about_us.html"),
                      name='about_us'),
                  path("",
                       TemplateView.as_view(template_name="home.html"),
                       name="home"),
                  path("contact-us/",
                       main.views.ContactUs.as_view(),
                       name="contact_us"),
                  path("accounts/", RedirectView.as_view(url='login', permanent=True, )),
                  path('accounts/signup/',
                       main.views.SignupView.as_view(),
                       name="signup"),
                  path("accounts/login/",
                       auth_views.LoginView.as_view(template_name="account/login.html",
                                                    form_class=main.forms.AuthenticationForm,
                                                    redirect_authenticated_user=True),
                       name="login",
                       kwargs={'redirect_authenticated_user': True}),
                  path("accounts/logout/",
                       auth_views.LogoutView.as_view(),
                       name="logout"),
                  path("accounts/profile/",
                       main.views.ProfileView.as_view(),
                       name="profile", ),
                  # path("authed/", RedirectView.as_view(url='home', permanent=False)),
                  path(
                      "address/",
                      main.views.AddressListView.as_view(),
                      name="address_list",
                  ),
                  path(
                      "address/create/",
                      main.views.AddressCreateView.as_view(),
                      name="address_create",
                  ),
                  path(
                      "address/<int:pk>/",
                      main.views.AddressUpdateView.as_view(),
                      name="address_update",
                  ),
                  path(
                      "address/<int:pk>/delete/",
                      main.views.AddressDeleteView.as_view(),
                      name="address_delete",
                  ),
                  path(
                      "add_to_basket/",
                      main.views.add_to_basket,
                      name="add_to_basket",
                  ),
                  path('basket/',
                       main.views.manage_basket,
                       name="basket"),
                  path(
                      "order/done/",
                      TemplateView.as_view(template_name="main/done_order.html"),
                      name="checkout_done",
                  ),
                  path(
                      "order/address_select/",
                      main.views.AddressSelectionView.as_view(),
                      name="address_select",
                  ),
                  # path(
                  #     "order_dashboard/",
                  #     main.views.OrderView.as_view(),
                  #     name="order_dashboard",
                  # ),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

audiobook/models.py
import os

from django.conf import settings
from django.core.exceptions import ValidationError
from django.db import models
from django.utils.translation import ugettext_lazy as _


class ActiveManager(models.Manager):
    def active(self):
        return self.filter(active=True)


class AudioBookTagManager(models.Manager):
    def get_by_natural_key(self, slug):
        return self.get(slug=slug)


class AudiobookTag(models.Model):
    name = models.CharField(max_length=40)
    slug = models.SlugField(max_length=48)
    description = models.TextField(blank=True)
    active = models.BooleanField(default=True)

    objects = AudioBookTagManager()

    def __str__(self):
        return self.name

    def natural_key(self):
        return (self.slug,)


def ext_validators(value):
    ext = '%s' % os.path.splitext(value.name)[-1]
    if ext.lower() not in settings.AUDIO_EXTENTIONS:
        message = _('Invalid format, please choose: %(ext)s') % {'ext': settings.AUDIO_EXTENTIONS}
        raise ValidationError(message)


class Audiobook(models.Model):
    name = models.CharField(max_length=500)
    written_by = models.CharField(max_length=250)
    narrated_by = models.CharField(max_length=250)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    slug = models.SlugField(max_length=48)
    tags = models.ManyToManyField(AudiobookTag, blank=True)
    active = models.BooleanField(default=True)
    date_updated = models.DateTimeField(auto_now=True)
    album_logo = models.FileField()
    # book_part = models.ForeignKey(AudioPart, on_delete=models.CASCADE, related_name='book_part')
    objects = ActiveManager()

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-name']


class AudioPart(models.Model):
    # contains audio in a audiobook mostly chapters
    audio_book = models.ForeignKey(Audiobook, on_delete=models.CASCADE, related_name='book_part')
    audio_name = models.CharField(max_length=250)
    audio_file = models.FileField(default='', validators=[ext_validators])

    def __str__(self):
        return self.audio_name


class AudiobookImage(models.Model):
    product = models.ForeignKey(Audiobook, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="product-images")

    thumbnail = models.ImageField(upload_to="product-thumbnails", null=True)

ebook/models.py
from __future__ import unicode_literals

import logging

from django.db import models
from welut.models import EbookConverter

logger = logging.getLogger(__name__)


class ActiveManager(models.Manager):
    def active(self):
        return self.filter(active=True)


class EbookTagManager(models.Manager):
    def get_by_natural_key(self, slug):
        return self.get(slug=slug)


class EbookTag(models.Model):
    name = models.CharField(max_length=40)
    slug = models.SlugField(max_length=48)
    description = models.TextField(blank=True)
    active = models.BooleanField(default=True)

    objects = EbookTagManager()

    def __str__(self):
        return self.name

    def natural_key(self):
        return (self.slug,)


class Ebook(models.Model):
    name = models.CharField(max_length=40)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    slug = models.SlugField(max_length=48)
    tags = models.ManyToManyField(EbookTag, blank=True)
    active = models.BooleanField(default=True)
    date_updated = models.DateTimeField(auto_now=True)
    ebook_file = models.ForeignKey(EbookConverter, related_name='ebook_file', on_delete=models.CASCADE, )

    objects = ActiveManager()

    def __str__(self):
        return self.name

    def get_files(self):
        """ return list images of ebook per-page """
        return self.ebook_file.get_files()

    class Meta:
        ordering = ['-name']


class EbookImage(models.Model):
    product = models.ForeignKey(Ebook, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="product-images")

    thumbnail = models.ImageField(upload_to="product-thumbnails", null=True)

audiobook/forms.py
from django import forms

from .models import Album, Song


class SongForm(forms.ModelForm):
    class Meta:
        model = Song
        fields = ['song_title', 'audio_file']


class AlbumForm(forms.ModelForm):
    class Meta:
        model = Album
        fields = ['artist', 'album_title', 'genre', 'album_logo']

audiobook/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.views.generic import TemplateView
from django.views.generic.list import ListView

from . import models


class AudioBookListView(ListView):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.tag = None

    template_name = "audiobook/audiobook_list.html"
    paginate_by = 4

    def get_queryset(self):
        try:
            tag = self.kwargs["tag"]
            if tag != "all":
                self.tag = get_object_or_404(models.AudiobookTag, slug=tag)
            if self.tag:
                audiobooks = models.Audiobook.objects.active().filter(tags=self.tag)
            else:
                audiobooks = models.Audiobook.objects.active()
        except KeyError:
            audiobooks = models.Audiobook.objects.active()
        return audiobooks.order_by("name")


class AudiobookAllShowView(LoginRequiredMixin, ListView):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.tag = None

    template_name = "audiobook/audiobook_viewer_list.html"
    paginate_by = 4

    def get_queryset(self):
        try:
            tag = self.kwargs["tag"]
            if tag != "all":
                self.tag = get_object_or_404(models.AudiobookTag, slug=tag)
            if self.tag:
                ebooks = models.Audiobook.objects.active().filter(tags=self.tag)
            else:
                ebooks = models.Audiobook.objects.active()
        except KeyError:
            ebooks = models.Audiobook.objects.active()
        return ebooks.order_by("name")


class AudiobookShowView(LoginRequiredMixin, TemplateView):
    template_name = 'audiobook/audiobook_viewer.html'

    def get_context_data(self, **kwargs):
        slug = self.kwargs["slug"]

        audiobook = models.Audiobook.objects.get(slug=slug)
        print(audiobook.book_part.all())
        return {'audiobook': audiobook}

templates/audiobook/audiobook_detail.html
{% extends "base.html" %}
{% block content %}
<h1>product</h1>
<table class="table">
    <tr>
        <th>Name</th>
        <td>{{ object.name }}</td>
    </tr>
    <tr>
        <th>Cover images</th>
        <td> {% for image in object.ebookimage_set.all %}
            <img alt="cover" src="{{ image.thumbnail.url }}"/>
            {% endfor %}
        </td>
    </tr>
    <tr>
        <th>Price</th>
        <td>{{ object.price }}</td>
    </tr>
    <tr>
        <th>Description</th>
        <td>{{ object.description|linebreaks }}</td>
    </tr>
    <tr>
        <th>Tags</th>
        <td>{{ object.tags.all|join:","|default:"No tags available" }}</td>
    </tr>
    <tr>
        <th>In stock</th>
        <td>{{ object.in_stock|yesno|capfirst }}</td>
    </tr>
    <tr>
        <th>Updated</th>
        <td>{{ object.date_updated|date:"F Y" }}</td>
    </tr>
</table>
<a href="{% url 'add_to_basket' %}?audiobook_id={{ object.id }}">Add to basket</a>
{% endblock content %}

templates/audiobook/audiobook_list.html
{% extends "base.html" %}
{% block content %}
<h1>AudioBooks</h1>
{% for audiobook in page_obj %}
<p>{{ audiobook.name }}</p>
<p><a href="{% url 'audiobook' audiobook.slug %}">See it here</a></p>
{% if not forloop.last %}
<hr>
{% endif %}
{% endfor %}
<nav>
    <ul class="pagination"> {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page={{page_obj.previous_page_number}}"> Previous</a></li>
        {% else %}
        <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
        {% endif %} {% for pagenum in page_obj.paginator.page_range %}
        <li class="page-item{% if page_obj.number == pagenum %} active{% endif %}">
            <a class="page-link" href="?page={{pagenum}}">{{pagenum}} </a>
        </li>
        {% endfor %} {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{page_obj.next_page_number}}">Next</a></li>
        {% else %}
        <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
        {% endif %}
    </ul>
</nav> {% endblock content %}

templates/audiobook/audiobook_viewer(copy).html
{% extends "base.html" %}
{% block content %}

{% load static %}
<h3>{{ audiobook.name }}</h3>

{% for audiobook_part in audiobook.book_part %}

<div class="card" oncontextmenu="return false;">
    <audio controls>
        <source src="{{ audiobook_part.audio_file.url }}" type="audio/mpeg">
        Your browser does not support the audio element.
    </audio>
</div>
{% if not forloop.last %}
<hr>
{% endif %}
{% endfor %}
{% endblock content %}

templates/audiobook/audiobook_viewer.html
{% extends "base.html" %}
{% block content %}

{% load static %}
<h3>{{ audiobook.name }}</h3>

{% for audiobook_part in audiobook.book_part.all %}

<div class="card" oncontextmenu="return false;">
    <h5 class="card-header">{{ audiobook_part.audio_file.name }}</h5>
    <audio controls>
        <source src="{{ audiobook_part.audio_file.url }}" type="audio/mpeg">
        Your browser does not support the audio element.
    </audio>
</div>
{% if not forloop.last %}
<hr>
{% endif %}
{% endfor %}
{% endblock content %}

templates/audiobook/audiobook_viewer_list.html
{% extends "base.html" %}
{% block content %}
<h1>My Audiobooks</h1>
{% for audiobook in page_obj %}
<p>{{ audiobook.name }}</p>
<p><a href="{% url 'audiobook_viewer' audiobook.slug %}">See it here</a></p>
{% if not forloop.last %}
<hr>
{% endif %}
{% endfor %}
<nav>
    <ul class="pagination"> {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page={{page_obj.previous_page_number}}"> Previous</a></li>
        {% else %}
        <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
        {% endif %} {% for pagenum in page_obj.paginator.page_range %}
        <li class="page-item{% if page_obj.number == pagenum %} active{% endif %}">
            <a class="page-link" href="?page={{pagenum}}">{{pagenum}} </a>
        </li>
        {% endfor %} {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{page_obj.next_page_number}}">Next</a></li>
        {% else %}
        <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
        {% endif %}
    </ul>
</nav> {% endblock content %}